---
title: "Game of Thrones Ratings"
author: "Rachel Bellflowers"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
   df_print: paged
   theme: readable
   code_folding: hide
 # pdf_document:
  #  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", warning = FALSE, message = FALSE) # echo false for pdf
library(tidyverse)
library(xml2)
library(rvest)
library(data.table)
library(ggthemes)
library(knitr)
```

### Introduction

```{r}
link_01 <- "https://www.imdb.com/title/tt0944947/episodes?season=1"
link_02 <- "https://www.imdb.com/title/tt0944947/episodes?season=2"
link_03 <- "https://www.imdb.com/title/tt0944947/episodes?season=3"
link_04 <- "https://www.imdb.com/title/tt0944947/episodes?season=4"
link_05 <- "https://www.imdb.com/title/tt0944947/episodes?season=5"
link_06 <- "https://www.imdb.com/title/tt0944947/episodes?season=6"
link_07 <- "https://www.imdb.com/title/tt0944947/episodes?season=7"
link_08 <- "https://www.imdb.com/title/tt0944947/episodes?season=8"

# Season 1

seas_1_episodes <- read_html(link_01) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_1_ratings <- read_html(link_01) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_1_dates <- read_html(link_01) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()

# Season 2

seas_2_episodes <- read_html(link_02) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_2_ratings <- read_html(link_02) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_2_dates <- read_html(link_02) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()


# Season 3

seas_3_episodes <- read_html(link_03) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_3_ratings <- read_html(link_03) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_3_dates <- read_html(link_03) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()

# Season 4

seas_4_episodes <- read_html(link_04) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_4_ratings <- read_html(link_04) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_4_dates <- read_html(link_04) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()

# Season 5

seas_5_episodes <- read_html(link_05) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_5_ratings <- read_html(link_05) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_5_dates <- read_html(link_05) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()

# Season 6

seas_6_episodes <- read_html(link_06) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_6_ratings <- read_html(link_06) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_6_dates <- read_html(link_06) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()

# Season 7

seas_7_episodes <- read_html(link_07) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_7_ratings <- read_html(link_07) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_7_dates <- read_html(link_07) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()

# Season 8

seas_8_episodes <- read_html(link_08) %>%
  html_nodes(xpath = "//*[(@id = \"episodes_content\")]//strong//a") %>%
  html_text()

seas_8_ratings <- read_html(link_08) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star\", \" \" )) and contains(concat( \" \", @class, \" \" ), concat( \" \", \"small\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"ipl-rating-star__rating\", \" \" ))]") %>%
  html_text()

seas_8_dates <- read_html(link_08) %>%
  html_nodes(xpath = "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"airdate\", \" \" ))]") %>%
  html_text()
```


```{r}
# Seasons

hmm <- replicate(n = 10, "Season 1", simplify = TRUE)
hmm2 <- replicate(n = 10, "Season 2", simplify = TRUE)
hmm3 <- replicate(n = 10, "Season 3", simplify = TRUE)
hmm4 <- replicate(n = 10, "Season 4", simplify = TRUE)
hmm5 <- replicate(n = 10, "Season 5", simplify = TRUE)
hmm6 <- replicate(n = 10, "Season 6", simplify = TRUE)
hmm7 <- replicate(n = 7, "Season 7", simplify = TRUE)
hmm8 <- replicate(n = 6, "Season 8", simplify = TRUE)

# Episode number

hmms <- replicate(n = 6, c(1:10), simplify = TRUE)
episode_num <- c(hmms, 1:7, 1:6)

# Combine into datatable

dates <- c(seas_1_dates, seas_2_dates, seas_3_dates, seas_4_dates, seas_5_dates, seas_6_dates, seas_7_dates, seas_8_dates)

episodes <- c(seas_1_episodes, seas_2_episodes, seas_3_episodes, seas_4_episodes, seas_5_episodes, seas_6_episodes, seas_7_episodes, seas_8_episodes)

ratings <- c(seas_1_ratings, seas_2_ratings, seas_3_ratings, seas_4_ratings, seas_5_ratings, seas_6_ratings, seas_7_ratings, seas_8_ratings)

seasons <- c(hmm, hmm2, hmm3, hmm4, hmm5, hmm6, hmm7, hmm8)

got <- data.table(seasons, episodes, episode_num, ratings, dates)

got$dates <- str_trim(got$dates)

# Changing data types

got$ratings <- as.numeric(got$ratings)

got$dates <- str_remove_all(got$dates, "\\.")
got$dates <- as.Date(got$dates, "%d %b %Y")
got$year <- as.numeric(format(got$dates, "%Y"))
```

```{r echo = FALSE}
got
```

```{r}
boxplot(got$ratings, main = "Boxplot of Ratings", col = "#529672")

# Less robust against outliers:

#mean(got$ratings) # 8.838356

#sd(got$ratings) # 0.9346167

# More robust against outliers:

#median(got$ratings) # 8.9

#IQR(got$ratings) # 0.7
```


```{r bar_chart, fig.height = 10, fig.width = 12}
ggplot(got, aes(factor(episode_num), ratings, fill = seasons)) +
  geom_col() +
  facet_grid(~seasons) +
  labs(title = "Ratings by Season of Game of Thrones", x = "Episode Number", y = "Rating") +
  theme_minimal() 
```

```{r}
ggplot(got, aes(factor(year), ratings)) +
  geom_col() +
  labs(title = "Ratings by Year", x = "Year", y = "Rating") +
  theme_minimal() +
  expand_limits(y=c(0, 10))
```





